version: "1.0"
info:
  model: int-scaffold
packages:
- name: Flow5Project
  gitServerName: GithubOrigin
  gitUrl: https://github.com/Munatri
  gitUsername: Munatri
  gitBranch: main
services:
- serviceName: project.flow5.integrations:t1
  packages:
  - name: Flow5Project
    version: "1.0"
- serviceName: pub.date:currentNanoTime
  packages:
  - name: WmPublic
    version: 11.1.0.0.1969
